/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../components/Auth.vue')['default']
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    Card: typeof import('./../components/ui/card/Card.vue')['default']
    CardContent: typeof import('./../components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./../components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../components/ui/card/CardTitle.vue')['default']
    Changelog: typeof import('./../components/Changelog.vue')['default']
    Comment: typeof import('./../components/Comment.vue')['default']
    Input: typeof import('./../components/ui/input/Input.vue')['default']
    Label: typeof import('./../components/ui/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./../components/ui/textarea/Textarea.vue')['default']
  }
}
